// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('nothernlights', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder()
          .withCapabilities({"browserName":"Chrome","browser_version":"81.0","os":"Windows","os_version":"10","resolution":"1024x768","project":"NothernLight Alert","browserstack.debug":true,"browserstack.console":"verbose","browserstack.networkLogs":true,"name":"nothernlights"})
          .usingServer(`https://${process.env.BROWSERSTACK_USERNAME}:${process.env.BROWSERSTACK_ACCESS_KEY}@hub-cloud.browserstack.com/wd/hub`)
          .build()
    vars = {}
  })
  afterEach(async function() {
    if (this.currentTest.state === 'passed')
          {await driver.executeScript('browserstack_executor: {"action": "setSessionStatus", "arguments": {"status":"passed"}}');}
        else
          {await driver.executeScript('browserstack_executor: {"action": "setSessionStatus", "arguments": {"status":"failed"}}');}
    await driver.quit();
  })
  it('nothernlights', async function() {
    await driver.get("https://www.softservenews.com/")
    await driver.findElement(By.css(".HideInfo1:nth-child(8) > b:nth-child(1)")).getText()
    await driver.findElement(By.css(".HideInfo1:nth-child(8) > b:nth-child(2)")).getText()
    assert(await driver.findElement(By.css(".HideInfo1:nth-child(8) > b:nth-child(3)")).getText() == "Quiet")
    await driver.findElement(By.css(".HideInfo1:nth-child(8) > b:nth-child(5)")).getText()
    await driver.findElement(By.css(".HideInfo1:nth-child(8) > b:nth-child(6)")).getText()
    assert(await driver.findElement(By.css(".HideInfo1 > b:nth-child(7)")).getText() == "Quiet")
    await driver.findElement(By.css(".HideInfo1:nth-child(8) > b:nth-child(9)")).getText()
    await driver.findElement(By.css(".HideInfo1:nth-child(8) > b:nth-child(10)")).getText()
    assert(await driver.findElement(By.css(".HideInfo1 > b:nth-child(11)")).getText() == "Quiet")
  })
})
